services:
  db_server:
    build:
      context: .
      dockerfile: ./db_service/Dockerfile
    container_name: transcendence_db_server
    volumes:
      - ./data:/usr/src/app/data   # solo montamos la DB
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendence_backend
    working_dir: /usr/src/app
    ports:
      - "8080:8080"