services:
  db_server:
    build:
      context: .
      dockerfile: ./db_service/Dockerfile
    container_name: transcendence_db_server
    volumes:
      - ./data:/usr/src/app/data   # solo montamos la DB
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendence_backend
    working_dir: /usr/src/app
    ports:
      # - "8080:8080"   # HTTP (per redirecció o testing)
      - "8443:8443"   # HTTPS (el port que usa api_server.js)

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendence_frontend
    working_dir: /usr/src/app
    ports:
      - "8081:8081"